export const SET_THEME_TO_LIGHT = "SET_THEME_TO_LIGHT";
export const SET_THEME_TO_DARK = "SET_THEME_TO_DARK";

//FORM ACTIONS
export const SHOW_FORM = "SHOW_FORM";
export const HIDE_FORM = "HIDE_FORM";
export const EDIT_FORM = "EDIT_FORM";
export const GET_DATE = "GET_DATE";
export const GET_PAYMENT_TERMS = "GET_PAYMENT_TERMS";
export const GET_LIST_ITEMS = "GET_LIST_ITEMS";

//INVOICE ACTIONS
export const GET_INVOICE = "GET_INVOICE";
export const RESET_INVOICE = "RESET_INVOICE";
export const TOGGLE_FILTER = "TOGGLE_FILTER";

// export const TOGGLE_CLICKED = "TOGGLE_CLICKED";
export const FILTER_INVOICE = "FILTER_INVOICE";

//ROUTE ACTIONS
export const TOGGLE_ROUTE = "TOGGLE_ROUTE";

//SUBMIT FORM ACTIONS
export const SUBMIT_PENDING = "SUBMIT_PENDING";

//INVOICE CONTROLS
export const SET_TO_PAID = "SET_TO_PAID";
export const DELETE_INVOICE = "DELETE_INVOICE";

//EDIT FORM ACTIONS
export const ADD_ITEM_TO_LIST = "ADD_ITEM_TO_LIST";
export const EDIT_ON_CHANGE = "EDIT_ON_CHANGE";
export const EDIT_LIST_DELETE = "EDIT_LIST_DELETE";
export const SET_EDIT_PAYMENT_TERMS = "SET_EDIT_PAYMENT_TERMS";
export const SET_EDIT_DATE = "SET_EDIT_DATE";
