// GENERAL ACTIONS
export const SET_THEME_TO_LIGHT = "SET_THEME_TO_LIGHT";
export const SET_THEME_TO_DARK = "SET_THEME_TO_DARK";
export const LOADING = "LOADING";
export const REMOVE_ERROR = "REMOVE_ERROR";

//FORM ACTIONS
export const SHOW_FORM = "SHOW_FORM";
export const HIDE_FORM = "HIDE_FORM";
export const EDIT_FORM = "EDIT_FORM";
export const GET_DATE = "GET_DATE";
export const GET_PAYMENT_TERMS = "GET_PAYMENT_TERMS";
export const GET_LIST_ITEMS = "GET_LIST_ITEMS";
export const ADD_NEW_ITEM_TO_LIST = "ADD_NEW_ITEM_TO_LIST";

//INVOICE ACTIONS
export const GET_INVOICE = "GET_INVOICE";
export const GET_SINGLE_INVOICE = "GET_SINGLE_INVOICE";
export const RESET_INVOICE = "RESET_INVOICE";
export const EMPTY_INVOICE_ON_LOGOUT = "EMPTY_INVOICE_ON_LOGOUT";
export const TOGGLE_FILTER = "TOGGLE_FILTER";
export const SET_ERROR = "SET_ERROR";
export const MARK_AS_PAID_LOADING = "MARK_AS_PAID_LOADING";
export const INVOICE_MARKED = "INVOICE_MARKED";

// export const TOGGLE_CLICKED = "TOGGLE_CLICKED";
export const FILTER_INVOICE = "FILTER_INVOICE";

//ROUTE ACTIONS
export const TOGGLE_ROUTE = "TOGGLE_ROUTE";

//SUBMIT FORM ACTIONS
export const SUBMIT_PENDING = "SUBMIT_PENDING";
export const SUBMIT_DRAFT = "SUBMIT_DRAFT";

//INVOICE CONTROLS
export const SET_TO_PAID = "SET_TO_PAID";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const SHOW_MODAL = "SHOW_MODAL";
export const CANCEL_DELETE = "CANCEL_DELETE";

//EDIT FORM ACTIONS
export const ADD_ITEM_TO_EDIT_LIST = "ADD_ITEM_TO_EDIT_LIST";
export const EDIT_ON_CHANGE = "EDIT_ON_CHANGE";
export const LIST_ON_CHANGE = "LIST_ON_CHANGE";
export const DELETE_LIST_ITEMS = "DELETE_LIST_ITEMS";
export const EDIT_LIST_DELETE = "EDIT_LIST_DELETE";
export const SET_EDIT_PAYMENT_TERMS = "SET_EDIT_PAYMENT_TERMS";
export const SET_EDIT_DATE = "SET_EDIT_DATE";
export const EDIT_INPUT = "EDIT_INPUT";

//ACTIONS FOR AUTHENTICATION
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const RESET_ERROR = "RESET_ERROR";
export const EMAIL_SENT = "EMAIL_SENT";
export const SET_FORGOT_PASSWORD_LINK = "SET_FORGOT_PASSWORD_LINK";
